export type CancelledPaymentDTO = {
   codigo: number;
   cod_per_anu: string;
   fec_anu: string;
   ip_anu: string;
   cod_cre: string;
   num_cuo: number;
   lug_rec: string;
   num_ric: number;
   cod_int: string;
   fec_pag: string;
   hor_pag: string;
   fec_doc: string;
   pago: number;
   pag_cap: number;
   pag_int: number;
   pag_seg: number;
   pag_seg_desgra: number;
   pag_mor: number;
   pag_mor_mor: number;
   pag_mor_com: number;
   pag_itf: number;
   pag_igv: number;
   dia_int: number;
   dia_mor: number;
   cod_ubi: string;
   tip_ope: string;
   ult_pag: string | null;
   cod_oei: string;
   enc_cap: number;
   enc_int: number;
   enc_mor: number;
   enc_mor_mor: number;
   enc_mor_com: number;
   enc_seg: number;
   enc_seg_desgra: number;
   cal_cap: number;
   cal_int: number;
   cal_rea: number;
   cal_mor: number;
   cal_imo: number;
   cal_gas: number;
   cap_por: number;
   int_por: number;
   cap_ven: number;
   int_ven: number;
   hor_rec: string | null;
   vou_eess: string | null;
   bru_eess: number | null;
   itf_ent: number | null;
   itf_sal: number | null;
   rec_net: number | null;
   com_cof: number | null;
   net_tot: number | null;
   cod_eess: string | null;
   nom_eess: string | null;
   swt_tip_pag: string;
   fec_reg: string;
   hor_reg: string;
   usu_reg: string;
   fec_reg_pag: string;
   fec_pag_rea: string;
   tip_pagcuo: string | null;
   swt_ser: string;
   can_ant: string | null;
   swt_can: string  | null;
   emp_tra: string;
   emp_ven: string;
   fue_fin_pag: string;
   mod_rea_pag: string;
   tip_amo_rop: string;
   fec_ven_pag: string;
   swt_mig_pag_ven: string;
   dia_int_ec: number;
   tip_cam: number;
   mor_enc: number;
   cue_ban: string  | null;
   ori_tip_cam: string;
   swt_pag_ban: string  | null;
   num_vou_ban: string  | null;
   id_pagcre: number;
   co_dispag: number;
   fe_propre: string;
   pag_bol_int: number;
   pag_seg_prev: number;
   cod_ds: number;
   usu_aut_con: string | null
};